author: Emacs@SMTH
url: http://smacs.github.io
title: 水木社区Emacs版

pygments:    true
markdown:    redcarpet

redcarpet:
  extensions: [no_intra_emphasis, tables, fenced_code_blocks, autolink, space_after_headers]
